name = "chatwii"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2024-11-21"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NODE_ENV = "production"
PUBLIC_SUPABASE_URL = "https://oabzjnoqrppbxmgqmtco.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYnpqbm9xcnBwYnhtZ3FtdGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MDI0MTQsImV4cCI6MjA3NDk3ODQxNH0.XVRvAy9dxdPWyZlb5-iV_QXTn0YmoxZWH10N7rchwhc"
PUBLIC_IMAGEKIT_PUBLIC_KEY = "public_o4AoAY8pBf4VqcJ4+YY7XXL+bco="
PUBLIC_IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/ChatWii"
PUBLIC_CAPTCHA_SITE_KEY = "0x4AAAAAAB4jwUskSLfD6nN0"
IMAGEKIT_PRIVATE_KEY = "private_X4n3xAifTYYuI5d0XqPmJNx93OM="
CAPTCHA_SECRET_KEY = "0x4AAAAAAB4jwZX_Tc-dwIDeJ4MtJD_rvgY"
